#!/usr/bin/env bash
#
# work-server-scan.sh — 扫描远程服务器上的 work-server 容器，生成 SSH 别名
#
# 功能：
#   1. 远程 SSH 到已知服务器列表，自动发现 work-server 容器
#   2. 查询每个容器的 tailscale IP
#   3. 生成 SSH config 条目（Host ssh-{server}-{port} → 走 tailscale 直连）
#
# 用法:
#   bash work-server-scan.sh              # 扫描并生成 SSH config
#   bash work-server-scan.sh --show       # 只显示不写入
#
# 环境变量:
#   WORK_SERVERS="210:10.10.18.210 211:10.10.18.211"   # 覆盖服务器列表
#
# 服务器配置: 编辑 SERVERS 数组或通过环境变量 WORK_SERVERS
#   export WORK_SERVERS="210:10.10.18.210 211:10.10.18.211"
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}$1${NC}"; }
ok()    { echo -e "  ${GREEN}✓${NC} $1"; }
warn()  { echo -e "  ${YELLOW}⚠${NC} $1" >&2; }
err()   { echo -e "  ${RED}✗${NC} $1" >&2; }

# ──────────────────────────────────────────────
# 服务器配置：label => SSH 地址
# 可通过 WORK_SERVERS 环境变量覆盖
# ──────────────────────────────────────────────
declare -A SERVERS
if [ -n "${WORK_SERVERS:-}" ]; then
  for entry in $WORK_SERVERS; do
    IFS=":" read -r label addr <<< "$entry"
    SERVERS["$label"]="$addr"
  done
else
  SERVERS["210"]="10.10.18.210"
  SERVERS["211"]="10.10.18.211"
  # SERVERS["ecs"]="39.102.52.1"
fi

SSH_CONFIG_FILE="${HOME}/.ssh/config"
TS_USER="lulizhi"    # 容器内用户名

usage() {
  cat <<EOF
扫描远程服务器上的 work-server 容器，生成 tailscale SSH 别名。

用法: bash $(basename "$0") [选项]

选项:
  --show      显示扫描结果，不写入 SSH config
  --help      显示此帮助

输出: 追加到 ${SSH_CONFIG_FILE}
EOF
  exit 1
}

# ──────────────────────────────────────────────
# 扫描单个服务器
# ──────────────────────────────────────────────
scan_server() {
  local label="$1"
  local addr="$2"
  local results=()
  local tmp_script

  info "🔍 扫描 ${label} (${addr})..."

  tmp_script=$(mktemp)
  cat > "$tmp_script" << 'REMOTE_CODE'
set -euo pipefail
docker ps --filter "name=lulizhi-work-server" --format "{{.Names}}" 2>/dev/null | while IFS= read -r name; do
  port=$(docker inspect "$name" --format '{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}' 2>/dev/null)
  ts_ip=$(docker exec "$name" tailscale ip -4 2>/dev/null || echo "")
  echo "${name}|${port}|${ts_ip}"
done
REMOTE_CODE

  while IFS='|' read -r container_name host_port ts_ip; do
    if [ -z "$container_name" ]; then
      continue
    fi
    results+=("${container_name#*-work-server-}|$host_port|$ts_ip")
  done < <(
    ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 "lulizhi@$addr" bash -s < "$tmp_script" 2>/dev/null
  )

  rm -f "$tmp_script"

  if [ ${#results[@]} -eq 0 ]; then
    warn "${label}: 未发现 work-server 容器或无法连接"
    return 1
  fi

  # 输出结果
  for entry in "${results[@]}"; do
    IFS='|' read -r instance host_port ts_ip <<< "$entry"
    if [ -n "$ts_ip" ]; then
      ok "${label}:${host_port} → ${instance} @ ${ts_ip}"
    else
      warn "${label}:${host_port} → ${instance} (tailscale 未连接)"
    fi
  done

  # 返回结果用于调用方
  echo "---SERVER:${label}---"
  for entry in "${results[@]}"; do
    echo "$entry"
  done
}

# ──────────────────────────────────────────────
# 生成 SSH config 条目
# ──────────────────────────────────────────────
generate_ssh_config() {
  local label="$1"
  local host_port="$2"
  local ts_ip="$3"
  local host_alias="ssh-${label}-${host_port}"

  cat <<CONFIG

# --- ${host_alias} (auto-generated by work-server-scan) ---
Host ${host_alias}
  HostName ${ts_ip}
  User ${TS_USER}
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ServerAliveInterval 60
CONFIG
}

# ──────────────────────────────────────────────
# 更新 SSH config（替换自动生成块）
# ──────────────────────────────────────────────
update_ssh_config() {
  local new_entries="$1"
  local marker_start="# BEGIN work-server-scan"
  local marker_end="# END work-server-scan"
  local tmpfile
  tmpfile=$(mktemp)

  if [ -f "$SSH_CONFIG_FILE" ]; then
    # 删除旧的自动生成块
    sed "/${marker_start}/,/${marker_end}/d" "$SSH_CONFIG_FILE" > "$tmpfile"
  else
    touch "$tmpfile"
  fi

  # 追加新块
  {
    echo ""
    echo "${marker_start}"
    echo "# Auto-discovered work-server containers via tailscale"
    echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "# Run 'bash scripts/docker/work-server-scan.sh' to refresh"
    echo "${new_entries}"
    echo "${marker_end}"
  } >> "$tmpfile"

  mkdir -p "$(dirname "$SSH_CONFIG_FILE")"
  mv "$tmpfile" "$SSH_CONFIG_FILE"
  chmod 600 "$SSH_CONFIG_FILE"
  ok "SSH config updated: ${SSH_CONFIG_FILE}"
}

# ──────────────────────────────────────────────
# 主流程
# ──────────────────────────────────────────────
SHOW_ONLY=false
case "${1:-}" in
  --show) SHOW_ONLY=true ;;
  --help|-h) usage ;;
  '') ;;
  *) echo "未知选项: $1"; usage ;;
esac

echo "══════════════════════════════════════"
echo "  work-server-scan — 容器发现 & SSH 别名生成"
echo "══════════════════════════════════════"
echo ""
info "服务器列表: ${!SERVERS[*]}"
echo ""

ALL_ENTRIES=""
FIRST_SERVER=true

for label in "${!SERVERS[@]}"; do
  addr="${SERVERS[$label]}"
  if [ "$FIRST_SERVER" = false ]; then
    # small delay between servers to avoid connection bursts
    sleep 1
  fi
  FIRST_SERVER=false

  # 扫描结果缓存在临时文件以解析
  tmp_result=$(mktemp)
  scan_server "$label" "$addr" > "$tmp_result" 2>&1 || true

  while IFS= read -r line; do
    if [[ "$line" == "---SERVER:"* ]]; then
      break
    fi
    echo "$line"
  done < "$tmp_result"

  # 解析结果
  in_section=false
  while IFS= read -r line; do
    if [[ "$line" == "---SERVER:${label}---" ]]; then
      in_section=true
      continue
    fi
    if [ "$in_section" = true ]; then
      IFS='|' read -r instance host_port ts_ip <<< "$line"
      if [ -n "$ts_ip" ] && [ -n "$host_port" ]; then
        entry=$(generate_ssh_config "$label" "$host_port" "$ts_ip")
        ALL_ENTRIES="${ALL_ENTRIES}${entry}"$'\n'
      fi
    fi
  done < "$tmp_result"

  rm -f "$tmp_result"
done

echo ""
info "══════════════════════════════════════"
echo ""

if [ -z "$ALL_ENTRIES" ]; then
  warn "没有发现任何可用的容器。"
  warn "请确认："
  warn "  1. 服务器已配置且可 SSH 访问"
  warn "  2. 服务器上已有运行中的 work-server 容器"
  warn "  3. 容器内 tailscale 已连接"
  exit 1
fi

if [ "$SHOW_ONLY" = true ]; then
  echo "以下 SSH 别名将生成："
  echo "$ALL_ENTRIES"
  echo ""
  info "使用: --show 未写入，实际执行不加参数即可写入 ~/.ssh/config"
else
  update_ssh_config "$ALL_ENTRIES"
  echo ""
  info "✅ 生效的别名："
  echo "$ALL_ENTRIES" | grep "^Host ssh-" | while read -r _ host; do
    echo "   ssh ${host}"
  done
  echo ""
  info "提示: 修改生效无需重启终端，直接用 ssh ssh-211-2225 连接"
fi
